name: Feature request
description: If you have a suggestion…
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting suggesting a feature!
  - type: checkboxes
    attributes:
      label: Is there an existing request?
      description: Please search open and closed issues to see if this request has already been made.
      options:
      - label: I have searched for this request
        required: true
  - type: textarea
    attributes:
      label: Describe the feature request
      description: A concise description of the request, potential solutions, and addtional context.
    validations:
      required: true
